#Use this dictionary to ensure values always go into the right cell. WIP.

B2B_clients = {
    1 : 'ABFF Client Support',
    2: 'Adjara Sport Client Support',
    3: 'Al Jazeera Client Support',
    4: 'AMCN HIDIVE Client Support',
    5: 'Anderlecht Client Support',
    6: 'Blast TV Client Support',
    7: 'Carlisle United Client Support',
    8: 'Core Sports Client Support',
    9: 'Dallas Mavericks Client Support',
    10: 'ELF Client Support',
    11: 'Endeavor Streaming Privacy',
    12: 'PLCS Client Support', #EPL
    13: 'EuroLeague Client Support',
    14: 'FEDCOM Client Support', #Skweek TV
    15: 'Supermotocross Client Support',
    16: 'Feyenoord Client Support',
    17: 'FIS Client Support',
    18: 'Indiana Fever Client Support',
    19: 'Ligue 1 Client Support',
    20: 'Longhorn Network Client Support',
    21: 'Racer+ Client Support', #Mav TV
    22: 'Melissa Wood Health Client Support',
    23: 'NBA Client Support',
    24: 'NESN Client Support',
    25: 'Newcastle United Client Support',
    26: 'NHRA Client Support',
    27: 'Northwoods League Client Support',
    28: 'NWSL Client Support',
    29: 'NZ Rugby Client Support',
    30: 'Oilers Client Support',
    31: 'PTO Client Support',
    32: 'R & A Client Support',
    33: 'Real Madrid Client Support',
    34: 'Shout! TV Client Support',
    35: 'Sky Sport Now Client Support',
    36: 'SPTV Client Support',
    37: 'Spurs TV Client Support',
    38: 'SuperLeague+ Client Support',
    39: 'TNA Plus Client Support',
    40: 'UEFA TV Client Support',
    41: 'UFC Client Support',
    42: 'UFC Fight Pass Brasil Client Support',
    43: 'Univision Now Client Support',
    44: 'USGA Client Support',
    45: 'WNBA League Pass Client Support',
    46: 'World Rugby Client Support',
    47: 'WWE Client Support',
}