B2C_clients_dict = {
    1: 'ABFF Play',
    2: 'Carlisle United TV',
    3: 'Dallas Mavericks TV',
    4: 'Dice Support Tickets',
    5: 'European League of Football',
    6: 'SkweekTV',
    7: 'SuperMotocross Video Pass',
    8: 'Fever Direct',
    9: 'Ligue 1',
    10: 'Longhorn Network',
    11: 'Racer+ Support',
    12: 'NBA', #Not on ZD
    13: 'Sportsnet Pittsburgh',
    14: 'Newcastle United TV',
    15: 'NWSL+',
    16: 'NZ Rugby',
    17: 'Oilers Plus',
    18: 'Sky Sport Now',
    19: 'SPURSPLAY',
    20: 'SuperLeague+',
    21: 'TNA+',
    22: 'UEFA TV',
    23: 'UFC',
    24: 'UFC Fight Pass Brasil',
    25: 'Univision Now',
    26: 'Univision TVE',
    27: 'WNBA', #Not in ZD
    28: 'Rugbypass.tv',
    29: 'WWE Network',
}